CREATE PROCEDURE FI_SP_VerificaCliente
	@CPF VARCHAR(11),
	@ID BIGINT = NULL,
	@ExisteCPF bit OUTPUT
AS
BEGIN
	SET @ExisteCPF = 0
	
	IF EXISTS(SELECT 1 FROM CLIENTES WHERE CPF = @CPF AND (ISNULL(@ID, 0) = 0 OR ID <> @ID))
		SET @ExisteCPF = 1
END

